### ISSUE TITLE
Website broken

### ISSUE THREAD

**Issue by milgner** [eclipse-birt/birt-website#56]
All links and the entry point `https://www.eclipse.org/birt/` point to `https://eclipse.github.io/birt-website/` but this produces a 404 status page from Github at the moment.

![image](https://github.com/eclipse-birt/birt-website/assets/160025/924db507-9d34-45da-bd17-eab1fd8d7e13)

**Comment by wimjongman** [comment]
Fixed. Thanks for reporting.

**Comment by wimjongman** [comment]
you may need to clear your browser cache because it caches 301 redirects.
